#!/bin/bash

cd $HOME

. ~/.bash_profile

PLAN9=${PLAN9:-/usr/local/plan9}

TERM=dumb export TERM
PAGER=nobs export PAGER
SHELL=rc export SHELL

pgrep -q plumber || $PLAN9/bin/plumber &

$PLAN9/bin/acme -a \
	-f /lib/font/bit/lucsans/euro.8.font,/mnt/font/LucidaGrande/25a/font \
	-F /usr/local/plan9/font/pelm/unicode.9.font,/mnt/font/Menlo-Regular/25a/font &
