#!/bin/sh

inflags=yes
flags=""
while [ $# != 0 -a $inflags = yes ]
do
	case "$1" in
	--)
		inflags=no
		shift
		;;
	-*)
		flags="$flags $1"
		shift
		;;
	-)
		inflags=no
		shift
		;;
	*)
		inflags=no
		;;
	esac
done

case $# in
0)
	echo 1>&2 'usage: g [flags] pattern [files]'
	exit 1
	;;
1)
	pattern="$1"
	paths="."
	;;
*)
	pattern="$1"
	shift
	paths="$@"
esac

files=`/usr/bin/find $paths | \
	9 grep '(\.[bcChlmsy]|\.asm|\.cc|\.cs|\.lx|\.cgi|\.pl|\.py|\.tex|\.ms|\.java|\.xy|\.go|\.goc)$' 2>/dev/null | \
	9 grep -v '\.tab?\.[ch]$'`
exec 9 grep -n $flags -- "$pattern" $files /dev/null
